AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable
  SuggestExtensions: false

Layout/ClosingParenthesisIndentation:
  Exclude:
    - 'lib/zxcvbn/frequency_lists.rb'

Layout/EndAlignment:
  EnforcedStyleAlignWith: start_of_line

Layout/FirstArgumentIndentation:
  Exclude:
    - 'lib/zxcvbn/frequency_lists.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'lib/zxcvbn/frequency_lists.rb'

Layout/MultilineMethodCallIndentation:
  Exclude:
    - 'lib/zxcvbn/frequency_lists.rb'

Lint/AmbiguousOperatorPrecedence:
  Enabled: false

Lint/UnderscorePrefixedVariableName:
  Enabled: false

Metrics:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/Next:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Style/RedundantReturn:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/NegatedIf:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/YodaCondition:
  Enabled: false
